sudo: false

language: java

jdk:
    - oraclejdk8

addons:
    apt:
        packages:
            - oracle-java8-installer

branches:
    only:
        - master

install: true

before_install:
    # node
    - nvm install 6
    # python
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes
    - conda create --quiet --name py3 python=3.6.1
    - conda create --quiet --name py2 python=2.7.13

script:
    # check java
    - java -version
    # check node
    - node --version
    - npm --version
    # check python
    - source activate py3
    - python --version
    - source activate py2
    - python --version
    - source deactivate
    # run gradle
    - chmod +x ./gradlew
    - ./gradlew
    # run ts
    - cd ts
    - npm install
    - node_modules/.bin/tsc
