sudo: false

language: java

jdk:
    - oraclejdk8

addons:
    apt:
        packages:
            - oracle-java8-installer

language: node_js

node_js:
    - '6'

branches:
    only:
        - master

install: true

script:
    - node --version
    - chmod +x ./gradlew
    - ./gradlew
