sudo: false

jdk:
    - oraclejdk8
addons:
    apt:
        packages:
            - oracle-java8-installer

node_js:
    - '6'

branches:
    only:
        - master

install: true

script:
    - chmod +x ./gradlew
    - ./gradlew
