sudo: false

language: java

jdk:
    - oraclejdk8

addons:
    apt:
        packages:
            - oracle-java8-installer

branches:
    only:
        - master

install: true

before_install:
    - nvm install 6

script:
    - java -version
    - node --version
    - npm --version
    - chmod +x ./gradlew
    - ./gradlew
